theme: jekyll-theme-slate
title: 神眼堪舆明师
description: 风水改命-阴宅-阳宅-禅定培训-驻颜术-健康管理
email:      renboxi@gmail.com
url: 
copyright:
year:       2022
name:       格局上医

# Multiple languages
gems:           ['jekyll-multiple-languages']
languages:          ['en', 'cn']
#设置不显示github 图标
github:
  is_project_page: false
